let stockProductos = [
    {id: 1, nombre: "Producto 1", tipo: "Prueba", cantidad: 1, desc: "", precio: 1000, img: ''},
    {id: 2, nombre: "Producto 2", tipo: "Prueba", cantidad: 1, desc: "", precio: 1100, img: ''},
    {id: 3, nombre: "Producto 3", tipo: "Prueba", cantidad: 1, desc: "", precio: 1200, img: ''},
    {id: 4, nombre: "Producto 4", tipo: "Prueba", cantidad: 1, desc: "", precio: 1400, img: ''},
    {id: 5, nombre: "Producto 5", tipo: "Prueba", cantidad: 1, desc: "", precio: 1600, img: ''},
    {id: 6, nombre: "Producto 6", tipo: "Prueba", cantidad: 1, desc: "", precio: 1800, img: ''},
    {id: 7, nombre: "Producto 7", tipo: "Prueba", cantidad: 1, desc: "", precio: 2000, img: ''},
    {id: 8, nombre: "Producto 8", tipo: "Prueba", cantidad: 1, desc: "", precio: 2500, img: ''},
    {id: 9, nombre: "Producto 9", tipo: "Prueba", cantidad: 1, desc: "", precio: 3000, img: ''},
    {id: 10, nombre: "Producto 10", tipo: "Prueba", cantidad: 1, desc: "", precio: 1200, img: ''},
    {id: 11, nombre: "Producto 11", tipo: "Prueba", cantidad: 1,desc: "", precio: 1400, img: ''},
    {id: 12, nombre: "Producto 12", tipo: "Prueba", cantidad: 1, desc: "", precio: 1600, img: ''},
    {id: 13, nombre: "Producto 13", tipo: "Prueba", cantidad: 1, desc: "", precio: 1800, img: ''},
    {id: 14, nombre: "Producto 14", tipo: "Prueba", cantidad: 1, desc: "", precio: 2000, img: ''},
    {id: 15, nombre: "Producto 15", tipo: "Prueba", cantidad: 1, desc: "", precio: 2200, img: ''},
    {id: 16, nombre: "Producto 16", tipo: "Prueba", cantidad: 1, desc: "", precio: 2500, img: ''},
    {id: 17, nombre: "Producto 17", tipo: "Prueba", cantidad: 1, desc: "", precio: 3000, img: ''},
    {id: 18, nombre: "Producto 18", tipo: "Prueba", cantidad: 1, desc: "", precio: 3500, img: ''},
    {id: 19, nombre: "Producto 19", tipo: "Prueba", cantidad: 1, desc: "", precio: 3500, img: ''},
    {id: 20, nombre: "Producto 20", tipo: "Prueba", cantidad: 1, desc: "", precio: 4000, img: ''},
    {id: 20, nombre: "Producto 21", tipo: "Prueba 2", cantidad: 1, desc: "", precio: 4500, img: ''},
]